### ISSUE TITLE
no 0 and 180 degrees

### ISSUE THREAD

**Issue by MikeDD2** [Audio-WestlakeU/FN-SSL#3]
Hello, thanks for this algorithm. I would like to ask if it can locate 0 and 180 degrees. I don’t know why the positioning results never show 0 and 180 degrees.

**Comment by wangyabo123** [comment]
Thank you for your attention to our work, the final estimation result is determined by the DP-IPD template, which was divided into templates at 5 ° intervals in the experiment (See the line 442 of the Module.py ). So it includes 0 ° and 180 °. You can give me more detail about your experiment logs that I will check  again to find the problem.

**Comment by MikeDD2** [comment]
Thanks much, I will try as you advice

**Comment by wangyabo123** [comment]
OK, any questions please let me know.
