### ISSUE TITLE
python Simu.py --train

### ISSUE THREAD

**Issue by JP199978** [Audio-WestlakeU/FN-SSL#5]
Dear author, thanks for your sharing of code and the state-of-the-art performance of Doa estimation.
I encountered the following error while executing the code python Simu.py --train and haven't been able to figure out how to resolve it. If you have time, could you help me check it?
(gpurir) ljp@meta:~/FN-SSL-main$ python Simu.py --train
make dir: /home/ljp/FN-SSL-main/data/train
10
  0%|                                                                                                                                                        | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "Simu.py", line 73, in <module>
    mic_signals, acoustic_scene = dataset[idx]
  File "/home/ljp/FN-SSL-main/Dataset.py", line 906, in __getitem__
    acoustic_scene = self.getRandomScene(idx)
  File "/home/ljp/FN-SSL-main/Dataset.py", line 926, in getRandomScene
    source_signal, vad = self.sourceDataset[idx]
  File "/home/ljp/FN-SSL-main/Dataset.py", line 299, in __getitem__
    utterance, fs = soundfile.read(utt_paths[n])
  File "/home/ljp/.conda/envs/gpurir/lib/python3.8/site-packages/soundfile.py", line 282, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/ljp/.conda/envs/gpurir/lib/python3.8/site-packages/soundfile.py", line 655, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/ljp/.conda/envs/gpurir/lib/python3.8/site-packages/soundfile.py", line 1209, in _open
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: {'128339': {'403-128339-0038': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0038.flac', '403-128339-0011': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0011.flac', '403-128339-0003': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0003.flac', '403-128339-0048': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0048.flac', '403-128339-0010': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0010.flac', '403-128339-0002': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0002.flac', '403-128339-0032': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0032.flac', '403-128339-0029': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0029.flac', '403-128339-0044': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0044.flac', '403-128339-0031': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0031.flac', '403-128339-0004': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0004.flac', '403-128339-0005': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0005.flac', '403-128339-0045': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0045.flac', '403-128339-0025': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0025.flac', '403-128339-0042': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0042.flac', '403-128339-0034': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0034.flac', '403-128339-0043': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0043.flac', '403-128339-0037': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0037.flac', '403-128339-0019': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0019.flac', '403-128339-0015': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0015.flac', '403-128339-0027': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0027.flac', '403-128339-0051': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0051.flac', '403-128339-0039': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0039.flac', '403-128339-0047': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0047.flac', '403-128339-0046': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0046.flac', '403-128339-0028': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0028.flac', '403-128339-0024': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0024.flac', '403-128339-0016': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0016.flac', '403-128339-0036': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0036.flac', '403-128339-0041': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0041.flac', '403-128339-0009': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0009.flac', '403-128339-0020': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0020.flac', '403-128339-0052': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0052.flac', '403-128339-0001': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0001.flac', '403-128339-0000': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0000.flac', '403-128339-0030': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0030.flac', '403-128339-0022': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0022.flac', '403-128339-0018': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0018.flac', '403-128339-0014': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0014.flac', '403-128339-0035': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0035.flac', '403-128339-0023': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0023.flac', '403-128339-0007': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0007.flac', '403-128339-0006': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0006.flac', '403-128339-0017': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0017.flac', '403-128339-0008': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0008.flac', '403-128339-0012': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0012.flac', '403-128339-0033': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0033.flac', '403-128339-0040': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0040.flac', '403-128339-0013': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0013.flac', '403-128339-0026': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0026.flac', '403-128339-0050': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0050.flac', '403-128339-0049': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0049.flac', '403-128339-0021': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/128339/403-128339-0021.flac'}, '216': {'403-216-0014': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0014.flac', '403-216-0028': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0028.flac', '403-216-0000': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0000.flac', '403-216-0010': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0010.flac', '403-216-0022': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0022.flac', '403-216-0024': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0024.flac', '403-216-0009': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0009.flac', '403-216-0008': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0008.flac', '403-216-0004': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0004.flac', '403-216-0019': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0019.flac', '403-216-0002': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0002.flac', '403-216-0013': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0013.flac', '403-216-0012': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0012.flac', '403-216-0021': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0021.flac', '403-216-0025': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0025.flac', '403-216-0023': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0023.flac', '403-216-0027': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0027.flac', '403-216-0015': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0015.flac', '403-216-0011': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0011.flac', '403-216-0018': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0018.flac', '403-216-0005': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0005.flac', '403-216-0003': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0003.flac', '403-216-0016': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0016.flac', '403-216-0001': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0001.flac', '403-216-0007': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0007.flac', '403-216-0026': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0026.flac', '403-216-0020': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0020.flac', '403-216-0017': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0017.flac', '403-216-0006': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/216/403-216-0006.flac'}, '126855': {'403-126855-0002': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0002.flac', '403-126855-0026': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0026.flac', '403-126855-0004': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0004.flac', '403-126855-0023': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0023.flac', '403-126855-0024': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0024.flac', '403-126855-0031': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0031.flac', '403-126855-0015': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0015.flac', '403-126855-0021': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0021.flac', '403-126855-0012': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0012.flac', '403-126855-0006': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0006.flac', '403-126855-0017': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0017.flac', '403-126855-0028': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0028.flac', '403-126855-0020': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0020.flac', '403-126855-0007': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0007.flac', '403-126855-0000': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0000.flac', '403-126855-0010': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0010.flac', '403-126855-0025': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0025.flac', '403-126855-0003': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0003.flac', '403-126855-0001': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0001.flac', '403-126855-0014': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0014.flac', '403-126855-0011': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0011.flac', '403-126855-0030': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0030.flac', '403-126855-0009': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0009.flac', '403-126855-0005': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0005.flac', '403-126855-0016': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0016.flac', '403-126855-0018': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0018.flac', '403-126855-0022': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0022.flac', '403-126855-0029': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0029.flac', '403-126855-0019': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0019.flac', '403-126855-0027': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0027.flac', '403-126855-0008': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0008.flac', '403-126855-0013': '/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100/403/126855/403-126855-0013.flac'}}

**Comment by wangyabo123** [comment]
Thanks for your attention to our work. This is the first time I've encountered such an error. I have also tested simu.py, and it works fine on my end. Based on the log you provided, I suggest you check whether the file path in

File "/home/ljp/FN-SSL-main/Dataset.py", line 299, in __getitem__ utterance, fs = soundfile.read(utt_paths[n])

is valid. The most likely issue I guess may be that your path is "/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100/LibriSpeech/train-clean-100", but in opt.py, it is set to "/home/ljp/FN-SSL-main/data/LibriSpeech/train-clean-100".  If you have further log information, please let me know so that I can help you resolve the issue well.

**Comment by JP199978** [comment]
Thank you very much for your response, it was indeed because of this reason.
