### ISSUE TITLE
Pretrained model download issue

### ISSUE THREAD

**Issue by sza-tth** [Audio-WestlakeU/FN-SSL#7]
Hi! Based on your publications, this method looks very promising, and I'd like to try it out. However, I'm unable to download the pretrained model from Baidu, as I don't have a Chinese phone number for registration (I'm based in Europe). Could you please share the pretrained models on an alternative platform, such as Google Drive?

Thank you very much!

**Comment by wangyabo123** [comment]
Hi, here is the Google Drive link.

**Comment by wangyabo123** [comment]
Hi, here is the google drive link, 1.FN-SSL with DP-IPD target: https://drive.google.com/file/d/1WEwb7seGb7UQ0Wc9pSUKz5PvUs5_tyTe/view?usp=drive_link 2. FN-SSL with DOA classification target: https://drive.google.com/file/d/19j2fevLe_1K9ZtqqSNp7RUme3UIEL2N2/view?usp=drive_link .
