### ISSUE TITLE
install gpuRIR

### ISSUE THREAD

**Issue by QinYcdc** [Audio-WestlakeU/FN-SSL#8]
Dear author, thank you for sharing the project, which is very helpful for my scientific research and study.
I am currently using Win11, and the highest supported version of cuda is 12.6. How should I choose the versions of cudatoolkit, pytorch, visual studio, camke and other related tools to install gpuRIR? Could you please tell me your experimental environment configuration?

**Comment by wangyabo123** [comment]
Thank you for your interest in our work. However, I don’t have experience installing gpuRIR on the Windows system. Perhaps you could find suitable environment configurations in the gpuRIR project. https://github.com/DavidDiazGuerra/gpuRIR

**Comment by QinYcdc** [comment]
> Thank you for your interest in our work. However, I don’t have experience installing gpuRIR on the Windows system. Perhaps you could find suitable environment configurations in the gpuRIR project. https://github.com/DavidDiazGuerra/gpuRIR

Thank you for your reply! Could you please share the environment in which you did the experiment? I plan to try it in Ubuntu. If it is convenient, please share the relevant pytorch version, cuda version, cmake version, and c++ compiler type and version. Thank you.
感谢您的回复！请问可以分享一下您在什么环境做的实验？我打算尝试在ubuntu环境下尝试一下，如果方便还请您分享一下相关的pytorch版本，环境下的cuda版本，cmake版本，还有c++编译器类型及版本，谢谢

**Comment by wangyabo123** [comment]
您好，我目前使用的服务器系统是Centos，系统cuda版本是12.3，gcc/g++ 8.3.1；安装gpuRIR环境下的torch版本是1.13.1；cmake版本3.22.4，实验用到的torch版本2.0.1
